
source 'https://rubygems.org'

gem 'serverspec'
gem 'fpm'
gem 'jgrep'
gem 'puppet-lint'
gem 'overcommit'
gem 'r10k'
gem 'ruby-lint'
gem 'rubocop'
gem 'yard'
gem 'concurrent-ruby'
gem 'rest-client'


# Lock to version provided by RedHat
gem 'json', '1.7.7'
