
source 'https://rubygems.org'

gem 'serverspec'
gem 'fpm'
gem 'jgrep'
gem 'puppet-lint'
gem 'overcommit'
gem 'r10k'
gem 'ruby-lint'
gem 'rubocop'
gem 'yard'
gem 'concurrent-ruby'
gem 'rest-client'
gem 'httpi'
gem 'curb'

git 'https://github.com/vinzent/onceover.git', :branch => 'json_el7_compat' do
  gem 'onceover'
end

# required by swagger client
gem 'typhoeus'


# Lock to version provided by RedHat
gem 'json', '1.7.7'

# rack >= 2.0.0 is not compatible with EL7 ruby
gem 'rack', '<2.0.0'
